"""empty message

Revision ID: 08ae7f78087e
Revises: ea99972d87f9
Create Date: 2022-06-25 23:25:14.490285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ae7f78087e'
down_revision = 'ea99972d87f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('questions_category_fkey', 'questions', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('questions_category_fkey', 'questions', 'categories', ['category'], ['id'])
    # ### end Alembic commands ###
