"""empty message

Revision ID: ea99972d87f9
Revises: 8a03a514865d
Create Date: 2022-06-16 15:10:08.031849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea99972d87f9'
down_revision = '8a03a514865d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'questions', 'categories', ['category'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    # ### end Alembic commands ###
